# Generated by Django 5.0.1 on 2024-02-06 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True)),
                ('last_education', models.CharField(blank=True, choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Diploma', 'Diploma'), ('Bsc', 'Bsc'), ('Honours', 'Honours'), ('Masters', 'Masters')], max_length=50, null=True)),
                ('teacher_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
