# Generated by Django 5.0.1 on 2024-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_course_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_education_status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Running', 'Running'), ('Stop', 'Stop')], max_length=20, null=True),
        ),
    ]
