# Generated by Django 5.0.1 on 2024-02-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_application_last_education_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='total_assignment',
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, choices=[('Upcoming', 'Upcoming'), ('Running', 'Running'), ('Complete', 'Complete'), ('Cancel', 'Cancel')], max_length=50, null=True),
        ),
    ]
